get: 
	scripts/run_get.sh 
	# all modules

clean: 
	scripts/run_clean.sh
	# all modules

format:
	scripts/run_format.sh
	# all modules

tests:
	scripts/run_tests.sh
	# all modules

analyze:
	scripts/run_analyze.sh
	# all modules

onlyclean:
	scripts/run_only_clean.sh
	# only module

onlyget:
	scripts/run_get_only.sh
	# only module


